In [9]:
import numpy as np

a = np.array([1,2,3])
b = np.array([[1],
                   [2],
                   [3]])
c = a*b
d=np.dot(a,b)
print(c)
print(d)
print(d.shape)

[[1 2 3]
 [2 4 6]
 [3 6 9]]
[14]
(1,)


In [12]:
e = ([3,4,5])
f = np.dot(e,e)
g = 3*3+4*4+5*5
print(f,'=',g)

50 = 50
